ansible@instance-4:~/ansible$ cat version_reading/tasks/main.yml
---
# task file for version_reading
  - name: fetch name/version
    shell: cat /etc/os-release
    register: response

  - name: print name/version
    debug:
      var: response.stdout_lines